### ISSUE TITLE
The JSON output file is not generated

### ISSUE THREAD

**Issue by jaxfellow** [jonathancs-tester/cypress10-cucumber-preprocessor#1]
Hello Jonathan,
Thank you for providing `cypress10-cucumber-preprocessor`
I've followed the instructions to configure it, which I assume was pretty similar to cypress versions < 10
Unfortunately there is no json files generated in cucumber-json folder.

here is my `package.json`:
```
"devDependencies": {
    "cypress10-cucumber-preprocessor": "^1.0.1"
  }
"cypress10-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  }
```
My `cypress.config.ts`:
```
const cucumber = require('cypress10-cucumber-preprocessor').default

async function setupNodeEvents(on, config) {
  on('file:preprocessor', cucumber());

  return config;
}

export default defineConfig({
  e2e: {
    setupNodeEvents,
    specPattern: 'cypress/e2e/**/*.feature',
  },
});
```

**Comment by jonathan-4iTester** [comment]
Hi @jaxfellow 

Thank you for sharing your problem. I tried to reproduce your problem in my local but the cypress-json folder generated with success, as image below:

![image](https://user-images.githubusercontent.com/66831974/197524656-db4ba69f-c9b6-428e-8754-38e9437727c4.png)

Could you please use this configuration in your package.json:

```
"cypress10-cucumber-preprocessor": {
    "step_definitions": "cypress/support/step_definitions",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  },
```

Any doubts, please contact me again

**Comment by jaxfellow** [comment]
```
"step_definitions": "cypress/support/step_definitions",
```
it seems like this is the only difference to my configuration which break the execution of my tests because I don't have global step definitions or a separate folder for it. 

Should that be responsible for not generating the JSON file?

**Comment by jonathan-4iTester** [comment]
If only use  `"nonGlobalStepDefinitions": true,`, your step definitions folder should be found in `cypress/e2e/common` according to documentation. This is not impacting the generation of JSON file.

**Comment by jaxfellow** [comment]
I double checked again my config and nothing seems to be different. Is there a way to debug json generation from my side and see what is going wrong with it?

**Comment by jonathancs-tester** [comment]
No, there is not. The source code is using cy.writeFile from Cypress function, as image below:

![image](https://user-images.githubusercontent.com/54334089/197846728-bd0c278b-9f66-4c0e-99a2-656c462059c1.png)

**Comment by jonathancs-tester** [comment]
No more comments.
