### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by vojtech-cerveny** [jonathancs-tester/cypress10-cucumber-preprocessor#2]
Hey, I wanted to ask - why? It is https://github.com/badeball/cypress-cucumber-preprocessor/ already, which do same thing, so I am wonder why are you created new package. 

Thanks and no offense! It seems, that your package knows how to generate JSON, which is something, what badeball dropped from code.

**Comment by vojtech-cerveny** [comment]
And one other question: Is this badeball framework v4.3.1 with some tweaks?

**Comment by jonathancs-tester** [comment]
Hi @vojtech-cerveny ,

Thanks for your question. This package is forked from https://github.com/TheBrainFamily/cypress-cucumber-example. I needed to create a new package for upgrade from Cypress 10. This package has only changes in path and filename according to the new features of Cypress 10.

**Comment by vojtech-cerveny** [comment]
Ok, thanks for answer!
